name: Bug Report
description: Report a bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's wrong?
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System Info
      placeholder: "GNOME Shell version, Extension version, OS"
    validations:
      required: true