name: Question
description: Ask for help
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: Ask your question here
    validations:
      required: true